version: '3'

services:
  fritzinfluxdb:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: adguard2influxdb
      network_mode: host
      restart: unless-stopped
      volumes:
        - ./my-adguard2influxdb.ini:/app/adguard2influxdb.ini